BlogApp.WebUI/Models/BlogModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BlogApp.WebUI.Models
{
    public class BlogModel
    {
    }
}

BlogApp.WebUI/Models/HomeModel.cs
using BlogApp.Entity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BlogApp.WebUI.Models
{
    public class HomeModel
    {
        public List<Blog> Sliders { get; set; }
        public List<Blog> Blogs { get; set; }
    }
}

BlogApp.WebUI/Controllers/BlogController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using BlogApp.Data.Abstract;
using BlogApp.Entity;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.CodeAnalysis.Differencing;

namespace BlogApp.WebUI.Controllers
{
    public class BlogController : Controller
    {
        private IBlogReporsitory _blogReporsitory;
        private ICategoryRepository _categoryRepository;
        public BlogController(IBlogReporsitory blogrepo, ICategoryRepository categoryrepo)
        {
            _blogReporsitory = blogrepo;
            _categoryRepository = categoryrepo;
        }
        public IActionResult Index(int? id,string q)
        {
            var query = _blogReporsitory.GetAll().Where(i => i.isApproved);

            if (id != null)
            {
                query = query.Where(i => i.isApproved && i.CategoryId == id);
            }
            if (!string.IsNullOrEmpty(q))
            {
                query = query.Where(i => i.Title.Contains(q) || i.Description.Contains(q) || i.Body.Contains(q));
            }

            return View(query.OrderByDescending(i => i.Date));
        }

        public IActionResult Details(int id)
        {
            return View(_blogReporsitory.GetByID(id));
        }

        [HttpGet]
        public IActionResult Create()
        {
            CategoryGetAll();
            return View(new Blog());
        }

        [HttpPost]
        public IActionResult Create(Blog entity)
        {
            entity.Date = DateTime.Now;
            if (ModelState.IsValid)
            {
                _blogReporsitory.SaveBlog(entity);
                TempData["message"] = $"{entity.Title} güncellenmiştr.";
                return RedirectToAction("List");
            }
            CategoryGetAll();
            return View(entity);
        }

        public IActionResult List()
        {
            return View(_blogReporsitory.GetAll());
        }
        [HttpGet]
        public IActionResult Edit(int id)
        {
            CategoryGetAll();
            return View(_blogReporsitory.GetByID(id));
        }
        [HttpPost]
        public async Task<IActionResult> Edit(Blog entity,IFormFile file)
        {
            if (ModelState.IsValid)
            {
                if (file != null)
                {
                    var path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot\\img", file.FileName);
                    using (var stream = new FileStream(path, FileMode.Create))
                    {
                        await file.CopyToAsync(stream);
                        entity.Image = file.FileName;
                    }
                }
                _blogReporsitory.SaveBlog(entity);
                TempData["message"] = $"{entity.Title} güncellendi.";
                return RedirectToAction("List");
            }
            CategoryGetAll();
            return View(entity);
        }
        [HttpGet]
        //public IActionResult AddOrUpdate(int? id)
        //{
        //    if (id == null)
        //    {
        //        CategoryGetAll();
        //        return View();
        //    }
        //    else
        //    {
        //        CategoryGetAll();
        //        return View(_blogReporsitory.GetByID((int)id));
        //    }
        //}

        //[HttpPost]
        //public IActionResult AddOrUpdate(Blog entity)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        _blogReporsitory.SaveBlog(entity);
        //        TempData["message"] = $"{entity.Title} güncellenmiştr.";
        //        return RedirectToAction("List");
        //    }
        //    CategoryGetAll();
        //    return View(entity);
        //}

        public void CategoryGetAll()
        {
            ViewBag.Categories = new SelectList(_categoryRepository.GetAll(), "Id", "Name");
        }

        public IActionResult Delete(int id)
        {
            return View(_blogReporsitory.GetByID(id));
        }
        [HttpPost,ActionName("Delete")]
        public IActionResult DeleteConfirmed(int id)
        {
            _blogReporsitory.DeleteBlog(id);
            return RedirectToAction("List");
        }
    }
}

BlogApp.WebUI/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BlogApp.Data.Abstract;
using BlogApp.Entity;
using Microsoft.AspNetCore.Mvc;

namespace BlogApp.WebUI.Controllers
{
    public class CategoryController : Controller
    {
        private ICategoryRepository _categoryRepository;
        private IBlogReporsitory _blogRepository;
        public CategoryController(ICategoryRepository categoryRepository, IBlogReporsitory blogReporsitory)
        {
            _categoryRepository = categoryRepository;
            _blogRepository = blogReporsitory;
        }
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult List()
        {
            return View(_categoryRepository.GetAll());
        }
        //[HttpGet]
        //public IActionResult Create()
        //{
        //    return View();
        //}
        //[HttpPost]
        //public IActionResult Create(Category entity)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        _categoryRepository.AddCategory(entity);
        //        return RedirectToAction("List");
        //    }

        //    return View(entity);
        //}

        [HttpGet]
        public IActionResult AddOrUpdate(int? id)
        {
            if (id == null)
            {
                return View(new Category());
            }
            else
            {
                return View(_categoryRepository.GetById((int)id));

            }
        }

        [HttpPost]
        public IActionResult AddOrUpdate(Category category)
        {
            if (ModelState.IsValid)
            {
                _categoryRepository.SaveCategory(category);

                TempData["message"] = $"{category.Name} güncellenmiştir.";
                return RedirectToAction("List");
            }


            return View(category);


        }



    }
}

BlogApp.WebUI/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BlogApp.Data.Abstract;
using BlogApp.Entity;
using BlogApp.WebUI.Models;
using Microsoft.AspNetCore.Mvc;

namespace BlogApp.WebUI.Controllers
{
    
    public class HomeController : Controller
    {
        private IBlogReporsitory blogReporsitory;
        public HomeController(IBlogReporsitory _blogReporsitory)
        {
            blogReporsitory = _blogReporsitory;
        }
        public IActionResult Index()
        {
            HomeModel model = new HomeModel();
            model.Blogs = blogReporsitory.GetAll().Where(i => i.isHome && i.isApproved).ToList();
            model.Sliders = blogReporsitory.GetAll().Where(i => i.isHome && i.isApproved && i.isSlider).ToList();
            return View(model);
        }
        public IActionResult List()
        {
            return View();
        }
     
        public IActionResult Details()
        {
            return View();
        }
    }
}

BlogApp.WebUI/ViewComponents/CategoryMenuViewComponent.cs
 using BlogApp.Data.Abstract;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BlogApp.WebUI.ViewComponents
{
    public class CategoryMenuViewComponent:ViewComponent
    {
        private ICategoryRepository _repository;
        public CategoryMenuViewComponent(ICategoryRepository repository)
        {
            _repository = repository;
        }

        public IViewComponentResult Invoke()
        {
            ViewBag.SelectedCAtegory = RouteData.Values["id"];
            return View(_repository.GetAll());
        }

    }
}

BlogApp.WebUI/Views/Blog/AddOrUpdate.cshtml
@model Blog
@{
    ViewData["Title"] = "Create";
     Layout = "~/Views/Shared/_Adminlayout.cshtml";
}
<div class="container">
    <h1>Create</h1>
    <br />

    <form method="post">
        <div class="form-group">
            <label asp-for="Title">Title</label>
            <input asp-for="Title" class="form-control">
        </div>
        <div class="form-group">
            <label asp-for="Description"></label>
            <textarea asp-for="Description" class="form-control"></textarea>
        </div>
        <div class="form-group">
            <label asp-for="Body"></label>
            <textarea asp-for="Body" class="form-control"></textarea>
        </div>
        <div class="form-group">
            <label asp-for="Image"></label>
            <input asp-for="Image" class="form-control">
        </div>
        <div class="form-check">
            <label class="form-check-label">
                <input asp-for="isApproved" class="form-check-input" />
                is Approved
            </label>
        </div>
        <div class="form-check">
            <label class="form-check-label">
                <input asp-for="isHome" class="form-check-input" />
                is Home
            </label>
        </div>
        <div class="form-check">
            <label class="form-check-label">
                <input asp-for="isSlider" class="form-check-input" />
                is Slider
            </label>
        </div>
        <div class="form-group">
            <label asp-for="CategoryId"></label>
            <select class="form-control" asp-for="CategoryId" asp-items="@ViewBag.Categories">
                <option disabled selected value="">Select Category</option>
            </select>
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
</div>

BlogApp.WebUI/Views/Blog/Create.cshtml
@model Blog
@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<div class="container">
    <h1>Create</h1>
    <br />

    <form method="post">
        <div class="form-group">
            <label asp-for="Title">Title</label>
            <input asp-for="Title" class="form-control">
        </div>
        <div class="form-group">
            <label asp-for="Description"></label>
            <textarea asp-for="Description" class="form-control"></textarea>
        </div>
        <div class="form-group">
            <label asp-for="CategoryId"></label>
            <select class="form-control" asp-for="CategoryId" asp-items="@ViewBag.Categories">
                <option disabled selected value="">Select Category</option>
            </select>
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
</div>

BlogApp.WebUI/Views/Blog/Delete.cshtml
@model Blog
@{
    ViewData["Title"] = "Delete";
     Layout = "~/Views/Shared/_Adminlayout.cshtml";
}

<h2>
    <b>@Model.Title</b> isimli kaydı silmek istiyor musunuz?
</h2>

<form asp-controller="Blog" asp-action="Delete" method="post">
    <input type="hidden" asp-for="Id" />
    <button type="submit" class="btn btn-primary">Delete</button>
</form>

BlogApp.WebUI/Views/Blog/Details.cshtml
@model Blog
@{
    ViewData["Title"] = "Details";
}

<div class="container mt-3">
    <div class="row">
        <div class="col-md-3">
            @await Component.InvokeAsync("CategoryMenu")
        </div>
        <div class="col-md-9">
            <div class="card mb-2">
                <div class="card-header">
                    @Model.Title
                </div>
                <img class="card-img-bottom" src="~/img/@Model.Image" alt="@Model.Body"/>
                <div class="card-body">
                    <h5 class="card-title">@Model.Title</h5>
                    <p class="card-text">@Model.Description</p>
                    <p class="card-text">@Html.Raw(Model.Body)</p>
                </div>
            </div>
        </div>
    </div>
</div>

BlogApp.WebUI/Views/Blog/Edit.cshtml
@model Blog
@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

@*@section scripts{
        <script src="~/lib/ckeditor.js"></script>
        <script>
            CKEDITOR.replace("Body")
        </script>
    }*@

@section scripts{
    <script src="~/lib/ckeditor/ckeditor.js"></script>
   
    <script>
        CKEDITOR.replace("Body");
    </script>
}

<div class="container">
    <h1>Edit</h1>
    <br />
    @*asp-controller="Blog" asp-action="Edit"*@
    <form asp-controller="Blog" asp-action="Edit" method="post" enctype="multipart/form-data">

        <input type="hidden" asp-for="Image" />

        <div class="form-group">
            <label asp-for="Title">Title</label>
            <input asp-for="Title" class="form-control">
        </div>
        <div class="form-group">
            <label asp-for="Description"></label>
            <textarea asp-for="Description" class="form-control"></textarea>
        </div>
        <div class="form-group">
            <label asp-for="Body"></label>
            <textarea asp-for="Body" class="form-control"></textarea>
        </div>



        <div class="form-group">
            <label>@Model.Image</label>
            <img src="~/img/@Model.Image" width="120" />
            <input type="file" name="file" id="file" class="form-control">
        </div>
        <div class="form-check">
            <label class="form-check-label">
                <input asp-for="isApproved" class="form-check-input" />
                is Approved
            </label>
        </div>
        <div class="form-check">
            <label class="form-check-label">
                <input asp-for="isHome" class="form-check-input" />
                is Home
            </label>
        </div>
        <div class="form-check">
            <label class="form-check-label">
                <input asp-for="isSlider" class="form-check-input" />
                is Slider
            </label>
        </div>
        <div class="form-group">
            <label asp-for="CategoryId"></label>
            <select class="form-control" asp-for="CategoryId" asp-items="@ViewBag.Categories">
                <option disabled selected value="">Select Category</option>
            </select>
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
</div>

BlogApp.WebUI/Views/Blog/Index.cshtml
@model IEnumerable<Blog>

@{
    ViewData["Title"] = "Index";
}


<div class="container mt-3">
    <div class="row">
        <div class="col-md-3">
            @await Component.InvokeAsync("CategoryMenu")
        </div>
        <div class="col-md-9">
            <partial name="_BlogList" for="@Model" />
        </div>
    </div>
</div>

BlogApp.WebUI/Views/Blog/List.cshtml
@model IEnumerable<Blog>
@{
    ViewData["Title"] = "List";
    Layout = "~/Views/Shared/_Adminlayout.cshtml";
}
<hr />
<div>
    <a asp-controller="Blog" asp-action="Create" class="btn btn-primary">content</a>
</div>
<hr />

<div class="container mt-3">
    <h2>Blog List</h2>
    <hr />
    <div class="row">
        <div class="col">
            @if (Model.Count() > 0)
            {
                <table class="table table-bordered table-striped">
                    <thead>
                        <tr>
                            <th>Id</th>
                            <th>Image</th>
                            <th>Title</th>
                            <th>Date</th>
                            <th>is Approved</th>
                            <th>is home</th>
                            <th>is Slider</th>
                            <th>Edit</th>
                            <th>Delete</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>@item.Id</td>
                                <td>
                                    <img src="~/img/@item.Image" width="100" />
                                </td>
                                <td>@item.Title</td>
                                <td>@item.Date</td>
                                <td>
                                    @if (item.isApproved)
                                    {
                                        <i class="fa fa-check" aria-hidden="true"></i>
                                    }
                                    else
                                    {
                                        <i class="fa fa-times" aria-hidden="true"></i>
                                    }


                                </td>
                                <td>
                                    @if (item.isHome)
                                    {
                                        <i class="fa fa-check" aria-hidden="true"></i>
                                    }
                                    else
                                    {
                                        <i class="fa fa-times" aria-hidden="true"></i>
                                    }
                                </td>
                                <td>
                                    @if (item.isSlider)
                                    {
                                        <i class="fa fa-check" aria-hidden="true"></i>
                                    }
                                    else
                                    {
                                        <i class="fa fa-times" aria-hidden="true"></i>
                                    }
                                </td>
                                <td>
                                    <a class="btn btn-primary btn-sm" asp-controller="Blog" asp-action="Edit" asp-route-id="@item.Id">
                                        Edit
                                    </a>
                                </td>
                                <td>
                                    <a class="btn btn-danger btn-sm" asp-controller="Blog" asp-action="Delete" asp-route-id="@item.Id">
                                        Delete.
                                    </a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            }
            else
            {
                <div class="alert alert-danger">
                    Blog Eklenmemiş.
                </div>
            }
        </div>
    </div>
</div>

BlogApp.WebUI/Views/Category/AddOrUpdate.cshtml
@model Category
@{
    ViewData["Title"] = "Create";
     Layout = "~/Views/Shared/_Adminlayout.cshtml";
}
<div class="container">
    <h1>Create Category</h1>
    <br />

    <form method="post">
        <div class="form-group">
            <label asp-for="Name">Name</label>
            <input asp-for="Name" class="form-control">
        </div>


        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
</div>

BlogApp.WebUI/Views/Category/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

BlogApp.WebUI/Views/Category/List.cshtml
@model IEnumerable<Category>
@{
    ViewData["Title"] = "List";
    Layout = "~/Views/Shared/_Adminlayout.cshtml";
}



<div class="container mt-3">
    <h2>Category List</h2>
    <hr />
    <div class="row">
        <div class="col">
            @if (Model.Count() > 0)
            {
                <table class="table table-bordered table-striped">
                    <thead>
                        <tr>
                            <th>Id</th>
                            <th>Name</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>@item.Id</td>
                                <td>@item.Name</td>
                                <td>
                                    <a class="btn btn-primary btn-sm" asp-controller="Category" asp-action="AddOrUpdate" asp-route-id="@item.Id">
                                        Details.
                                    </a>
                                    <a class="btn btn-danger btn-sm" asp-controller="Category" asp-action="Delete" asp-route-id="@item.Id">
                                        Delete.
                                    </a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            }
            else
            {
                <div class="alert alert-danger">
                    Category Eklenmemiş.
                </div>
            }
        </div>
    </div>
</div>

BlogApp.WebUI/Views/Home/Index.cshtml
@model HomeModel
@{
    ViewData["Title"] = "Index";
}


<div class="container my-4">
    <div class="row">
        <div class="col-md-3">
            @await Component.InvokeAsync("CategoryMenu")
        </div>
        <div class="col-md-9">
            @Html.Partial("_Slider", Model.Sliders)
            @Html.Partial("_BlogList", Model.Blogs)
        </div>
    </div>
</div>

BlogApp.WebUI/Views/Shared/Components/CategoryMenu/Default.cshtml
@model IEnumerable<Category>

<div class="list-group">
    @foreach (var item in Model)
    {
        <div class="list-group">
            <a asp-controller="Blog"
               asp-action="Index"
               asp-route-id="@item.Id"
               class="list-group-item list-group-item @(ViewBag.SelectedCategory == item.Id.ToString() ? "active":"")">
                @item.Name
            </a>
        </div>
    }
</div>

BlogApp.WebUI/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>



    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <link href="~/css/bundle.min.css" rel="stylesheet" />

</head>
<body>

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
            <a class="navbar-brand" href="#">Admin</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon">hadi</span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="/">User Page <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/blog/list">Blog</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/Category/list">Category</a>
                    </li>

                </ul>
                <form class="form-inline my-2 my-lg-0">
                    <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                    <button class="btn btn-outline-info my-2 my-sm-0" type="submit">Search</button>
                </form>
            </div>
        </div>
    </nav>

    <div id="main" class="container">
        @if (TempData["message"] != null)
        {
            <div class="alert alert-success">
                @TempData["message"]
            </div>
        }
        @RenderBody()
    </div>

    @RenderSection("scripts", false)



    <script src="~/js/bundle.min.js"></script>
</body>
</html>

BlogApp.WebUI/Views/Shared/_BlogList.cshtml
@model IEnumerable<Blog>

@if (Model.Count() == 0)
{
    <div class="alert alert-warning">Kayıt Yok</div>
}
else
{
    @foreach (var item in Model)
    {
        <div class="card mb-2">
            <div class="card-header">
                @item.Title
            </div>
            <img class="card-img-top" src="~/img/@item.Image" alt="Card iamge cap"/>
            <div class="card-body">
                <h5 class="card-title">@item.Title</h5>
                <p class="card-text">@item.Description</p>
                <a asp-controller="Blog" asp-action="Details" asp-route-id="@item.Id" class="btn btn-primary">Blog Details</a>
            </div>
        </div>
    }

}

BlogApp.WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>


    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    @*<link href="~/css/bundle.min.css" rel="stylesheet" />*@

</head>
<body>

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
            <a class="navbar-brand" href="/">Blog</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon">hadi</span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/blog/list">Blog</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/Category/list">Category</a>
                    </li>

                </ul>

                <partial name="_SearchBox" />
            </div>
        </div>
    </nav>

    <div id="main" class="container">
        @if (TempData["message"] != null)
        {
            <div class="alert alert-success">
                @TempData["message"]
            </div>
        }
        @RenderBody()
    </div>

    
    <script src="~/js/jquery.js"></script>
    <script src="~/js/bootstrap.js"></script>
    @RenderSection("scripts",false)
   



</body>
</html>

BlogApp.WebUI/Views/Shared/_SearchBox.cshtml
<form asp-controller="Blog" asp-action="Index" method="get" class="form-inline my-2 my-lg-0">
    <input id="q" name="q" class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
    <button class="btn btn-outline-info my-2 my-sm-0" type="submit">Search</button>
</form>

BlogApp.WebUI/Views/Shared/_Slider.cshtml
@model IEnumerable<Blog>

<div id="carouselExampleIndicators" class="carousel slide mb-3" data-ride="carousel">
    <ol class="carousel-indicators">

        @for (int i = 0; i < Model.Count(); i++)
        {
            if (i == 0)
            {
                <li data-target="#carouselExampleIndicators" data-slide-to="@i" class="active"></li>
            }
            else
            {
                <li data-target="#carouselExampleIndicators" data-slide-to="@i"></li>
            }
        }

    </ol>
    <div class="carousel-inner" role="listbox">

        @{ var index = 0;}
        @foreach (var item in Model)
        {
            if (index == 0)
            {
                <div class="carousel-item active">
                    <img class="d-block img-fluid" src="~/img/@item.Image" alt="@item.Title">
                    <div class="carousel-caption d-none d-md-block">
                        <h3>@item.Title</h3>
                        <p>@item.Description</p>
                    </div>
                </div>

                index++;
            }
            else
            {
                <div class="carousel-item">
                    <img class="d-block img-fluid" src="~/img/@item.Image" alt="@item.Title">
                    <div class="carousel-caption d-none d-md-block">
                        <h3>@item.Title</h3>
                        <p>@item.Description</p>
                    </div>
                </div>
            }

        }

    </div>
    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>